apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  app-key: {{ .Values.secrets.appKey | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  db-username: {{ .Values.secrets.dbUsername | quote }}
  db-password: {{ .Values.secrets.dbPassword | quote }}
